version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./deploy/dockerfile
    ports:
      - "${DOCKER_PORT:-8012}:${APP_PORT:-8000}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_OUT_PORT:-54333}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
