"""add visible flag

Revision ID: 30ea6ed3e978
Revises: 8cb60ef46552
Create Date: 2024-10-22 14:39:06.532631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ea6ed3e978'
down_revision: Union[str, None] = '8cb60ef46552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_files', sa.Column('visible', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'schedule_files', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_files', type_='unique')
    op.drop_column('schedule_files', 'visible')
    # ### end Alembic commands ###
