"""Add new models

Revision ID: 4e9049e19c22
Revises: b312784c1681
Create Date: 2024-12-05 22:38:15.640599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9049e19c22'
down_revision: Union[str, None] = 'b312784c1681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc_disc',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_group',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_prep',
    sa.Column('fio', sa.Text(), nullable=False),
    sa.Column('chair', sa.Text(), nullable=True),
    sa.Column('degree', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18_days',
    sa.Column('semcode', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sc_rasp18_days_semcode'), 'sc_rasp18_days', ['semcode'], unique=False)
    op.create_index('ix_sc_rasp18_days_semcode_day', 'sc_rasp18_days', ['semcode', 'day'], unique=False)
    op.create_table('students',
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18',
    sa.Column('semcode', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('worktype', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('timestart', sa.Text(), nullable=False),
    sa.Column('timeend', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['sc_disc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sc_rasp18_semcode'), 'sc_rasp18', ['semcode'], unique=False)
    op.create_table('sc_rasp7',
    sa.Column('semcode', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('pair', sa.Integer(), nullable=False),
    sa.Column('weeksarray', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('weekstext', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['sc_disc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sc_rasp7_semcode'), 'sc_rasp7', ['semcode'], unique=False)
    op.create_index('ix_sc_rasp7_semcode_version', 'sc_rasp7', ['semcode', 'version'], unique=False)
    op.create_table('sc_rasp18_groups',
    sa.Column('rasp18_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sc_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rasp18_id'], ['sc_rasp18.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18_info',
    sa.Column('rasp18_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rasp18_id'], ['sc_rasp18.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18_move',
    sa.Column('rasp18_dest_id', sa.Integer(), nullable=False),
    sa.Column('src_day_id', sa.Integer(), nullable=False),
    sa.Column('src_pair', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rasp18_dest_id'], ['sc_rasp18.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18_preps',
    sa.Column('rasp18_id', sa.Integer(), nullable=False),
    sa.Column('prep_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['prep_id'], ['sc_prep.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rasp18_id'], ['sc_rasp18.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp18_rooms',
    sa.Column('rasp18_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rasp18_id'], ['sc_rasp18.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp7_groups',
    sa.Column('rasp7_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subgroup', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['sc_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rasp7_id'], ['sc_rasp7.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp7_preps',
    sa.Column('rasp7_id', sa.Integer(), nullable=False),
    sa.Column('prep_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['prep_id'], ['sc_prep.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rasp7_id'], ['sc_rasp7.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sc_rasp7_rooms',
    sa.Column('rasp7_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['rasp7_id'], ['sc_rasp7.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc_rasp7_rooms')
    op.drop_table('sc_rasp7_preps')
    op.drop_table('sc_rasp7_groups')
    op.drop_table('sc_rasp18_rooms')
    op.drop_table('sc_rasp18_preps')
    op.drop_table('sc_rasp18_move')
    op.drop_table('sc_rasp18_info')
    op.drop_table('sc_rasp18_groups')
    op.drop_index('ix_sc_rasp7_semcode_version', table_name='sc_rasp7')
    op.drop_index(op.f('ix_sc_rasp7_semcode'), table_name='sc_rasp7')
    op.drop_table('sc_rasp7')
    op.drop_index(op.f('ix_sc_rasp18_semcode'), table_name='sc_rasp18')
    op.drop_table('sc_rasp18')
    op.drop_table('students')
    op.drop_index('ix_sc_rasp18_days_semcode_day', table_name='sc_rasp18_days')
    op.drop_index(op.f('ix_sc_rasp18_days_semcode'), table_name='sc_rasp18_days')
    op.drop_table('sc_rasp18_days')
    op.drop_table('sc_prep')
    op.drop_table('sc_group')
    op.drop_table('sc_disc')
    # ### end Alembic commands ###
