"""Update data

Revision ID: b312784c1681
Revises: 30ea6ed3e978
Create Date: 2024-11-19 13:37:24.876312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b312784c1681'
down_revision: Union[str, None] = '30ea6ed3e978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_files', sa.Column('standardized_content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_files', 'standardized_content')
    # ### end Alembic commands ###
