"""update ScRasp7

Revision ID: d8826007fd2b
Revises: 9c764ab96ad8
Create Date: 2024-12-10 16:00:11.685453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8826007fd2b'
down_revision: Union[str, None] = '9c764ab96ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sc_disc', ['id'])
    op.create_unique_constraint(None, 'sc_group', ['id'])
    op.create_unique_constraint(None, 'sc_prep', ['id'])
    op.create_unique_constraint(None, 'sc_rasp18', ['id'])
    op.create_foreign_key(None, 'sc_rasp18', 'sc_rasp18_days', ['day_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'sc_rasp18_days', ['id'])
    op.create_index('ix_sc_rasp18_groups_group_rasp', 'sc_rasp18_groups', ['group_id', 'rasp18_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp18_groups', ['id'])
    op.create_unique_constraint(None, 'sc_rasp18_info', ['id'])
    op.create_unique_constraint(None, 'sc_rasp18_move', ['id'])
    op.create_index('ix_sc_rasp18_preps_prep_rasp', 'sc_rasp18_preps', ['prep_id', 'rasp18_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp18_preps', ['id'])
    op.create_index('ix_sc_rasp18_rooms_room_rasp', 'sc_rasp18_rooms', ['room', 'rasp18_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp18_rooms', ['id'])
    op.add_column('sc_rasp7', sa.Column('worktype', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'sc_rasp7', ['id'])
    op.create_index('ix_sc_rasp7_groups_group_sem', 'sc_rasp7_groups', ['group_id', 'rasp7_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp7_groups', ['id'])
    op.create_index('ix_sc_rasp7_preps_prep_rasp', 'sc_rasp7_preps', ['prep_id', 'rasp7_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp7_preps', ['id'])
    op.create_index('ix_sc_rasp7_rooms_room_rasp', 'sc_rasp7_rooms', ['room', 'rasp7_id'], unique=False)
    op.create_unique_constraint(None, 'sc_rasp7_rooms', ['id'])
    op.create_unique_constraint(None, 'students', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'sc_rasp7_rooms', type_='unique')
    op.drop_index('ix_sc_rasp7_rooms_room_rasp', table_name='sc_rasp7_rooms')
    op.drop_constraint(None, 'sc_rasp7_preps', type_='unique')
    op.drop_index('ix_sc_rasp7_preps_prep_rasp', table_name='sc_rasp7_preps')
    op.drop_constraint(None, 'sc_rasp7_groups', type_='unique')
    op.drop_index('ix_sc_rasp7_groups_group_sem', table_name='sc_rasp7_groups')
    op.drop_constraint(None, 'sc_rasp7', type_='unique')
    op.drop_column('sc_rasp7', 'worktype')
    op.drop_constraint(None, 'sc_rasp18_rooms', type_='unique')
    op.drop_index('ix_sc_rasp18_rooms_room_rasp', table_name='sc_rasp18_rooms')
    op.drop_constraint(None, 'sc_rasp18_preps', type_='unique')
    op.drop_index('ix_sc_rasp18_preps_prep_rasp', table_name='sc_rasp18_preps')
    op.drop_constraint(None, 'sc_rasp18_move', type_='unique')
    op.drop_constraint(None, 'sc_rasp18_info', type_='unique')
    op.drop_constraint(None, 'sc_rasp18_groups', type_='unique')
    op.drop_index('ix_sc_rasp18_groups_group_rasp', table_name='sc_rasp18_groups')
    op.drop_constraint(None, 'sc_rasp18_days', type_='unique')
    op.drop_constraint(None, 'sc_rasp18', type_='foreignkey')
    op.drop_constraint(None, 'sc_rasp18', type_='unique')
    op.drop_constraint(None, 'sc_prep', type_='unique')
    op.drop_constraint(None, 'sc_group', type_='unique')
    op.drop_constraint(None, 'sc_disc', type_='unique')
    # ### end Alembic commands ###
