FROM python:3.12-alpine

WORKDIR /opt/src/

RUN apk update

RUN pip install --upgrade pip

RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root

RUN apk add --no-cache gcc build-base libffi-dev musl-dev postgresql-dev
COPY ./ ./
CMD alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8000 --log-level info
